inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 40
Metrics/LineLength:
  Max: 200
Style/Documentation:
  Enabled: false