version: '3'
services:
  db:
    image: postgres:11.2
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
    ports:
      - '5432:5432'
    volumes:
      - datavol:/var/lib/postgresql/data
  web:
    build: .
    user: "501:501"
    command: /bin/sh -c "rm -f /home/ec2-user/environment/academic_app/tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/academic_app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
      - "POSTGRES_DB=academic_app_dev"
    depends_on:
      - db
volumes:
  datavol:

