version: '3'
services:
  db:
    image: postgres:11.2
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
      - "POSTGRES_DB=academic_app_dev"
    ports:
      - '5432:5432'
    volumes:
      - datavol:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/academic_app
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    depends_on:
      - db
volumes:
  datavol:

