version: '3'
services:
  db:
    image: postgres:11.4
    ports:
      - '5432:5432'
    volumes:
      - datavol:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh -c "rm -f /home/ec2-user/environment/academic_app/tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/academic_app
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  datavol:
